# Generated by Django 5.1.4 on 2025-02-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouncePerfect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The full text sample for practice', max_length=1000)),
                ('title', models.CharField(help_text='A short title or description for the sample', max_length=200)),
                ('actual_pronunciation', models.FileField(blank=True, help_text='Optional audio file of the correct pronunciation', null=True, upload_to='pronunciations/actual/')),
                ('your_pronunciation', models.FileField(blank=True, help_text='Optional audio file of the user’s pronunciation', null=True, upload_to='pronunciations/user/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the sample was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the sample was last updated')),
            ],
            options={
                'verbose_name': 'Practice Sample',
                'verbose_name_plural': 'Practice Samples',
            },
        ),
    ]
