# Generated by Django 5.1.4 on 2025-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronouncePerfect', '0003_set_language_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesample',
            name='language',
            field=models.CharField(choices=[('eng', 'English'), ('np', 'Nepali')], default='eng', help_text='Select the language (English or Nepali)', max_length=3),
        ),
    ]
