"""
Django settings for Mispronunciation project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o!*kok3_ub+z0^8!2tfw-xz&h33wmz%df8+(+&o@u84%dfd1+@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'pronouncePerfect',
    'corsheaders',
]

# CSRF settings for development - Allow all origins (with valid scheme)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',  # Local development origin
    'http://localhost:5174',  # Adjust for your frontend port if necessary
    'http://localhost:5173',  # Adjust for your frontend port if necessary
    'http://127.0.0.1:8000',  # Localhost alternative
    'http://127.0.0.1:5174',  # Adjust for your frontend port if necessary
    'http://localhost:5173',  # Another localhost alternative
]

CSRF_COOKIE_SECURE = True  # Don't enforce HTTPS for local development
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the cookie
CSRF_COOKIE_SAMESITE = 'None'  # Allow cross-site requests (relaxed for local dev)

CORS_ALLOW_CREDENTIALS = True  # Allow cookies in cross-origin requests

# CORS allowed origins - Specify scheme (http:// or https://)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5174",  # Adjust for your frontend port if necessary
    "http://localhost:5173",  # Adjust for your frontend port if necessary
    "http://127.0.0.1:5174",  # Adjust for your frontend port if necessary
    "http://127.0.0.1:5173",  # Adjust for your frontend port if necessary
    "http://localhost:8000",   # Django backend
    "http://127.0.0.1:8000",  # Django backend alternative
]

# Allow CORS from all origins (unsafe for production)
CORS_ALLOW_ALL_ORIGINS = True  # This will allow all domains to access your API.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Mispronunciation.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
             os.path.join(BASE_DIR, 'templates'),  #pointing to template folder
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mispronunciation.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

## --media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Path to the fine-tuned model
MODEL_DIR = os.path.join(BASE_DIR, 'pronouncePerfect', 'models', 'fine_tuned_model')
NEP_MODEL_DIR = os.path.join(BASE_DIR, 'pronouncePerfect', 'models', 'wav2vec_nep_model')
# W2V_EN_MODEL_DIR = os.path.join(BASE_DIR, 'pronouncePerfect', 'models', 'wav2vec_en_model')

# WHISPER_NEP_MODEL_DIR = os.path.join(BASE_DIR, 'pronouncePerfect', 'models', 'whisper_nep_model')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
